---

# Create target group

  - name: Create target group
    elb_target_group:
      region: "{{ aws_alb_tg_region }}"
      name: "{{ aws_alb_tg_tg_name }}"
      protocol: "{{ aws_alb_tg_tgprotocol | default('https') }}"
      port: "{{ aws_alb_tg_tgport | default('443') }}"
      vpc_id: "{{ aws_alb_tg_vpcid | default(omit) }}"
      health_check_path: /
      health_check_protocol: "{{ aws_alb_tg_tgprotocol | default('https') }}"
      health_check_port: "{{ aws_alb_tg_tgport | default('443') }}"
      health_check_interval: 5
      health_check_timeout: 3
      healthy_threshold_count: 2
      successful_response_codes: "200"
      state: "{{ aws_alb_tg_tgstate | default('present') }}"
      wait_timeout: 200
      modify_targets: false
      wait: True
    tags:
      - target_group
    register: tg

  - name: register elb targets  
    elb_target:
      region: "{{ aws_alb_tg_region }}"
      target_group_name: "{{ aws_alb_tg_tg_name }}"
      target_id: "{{ item }}"
      state: present
    with_items: "{{ aws_alb_tg_alb_instance_ids | default(aws_alb_tg_fact_instance_ids) }}"
    tags:
      - target_group
